### PR TITLE
Fix a bug

### PR DESCRIPTION
**Pull request by drekamor**
@RedDevel2

### CODE REVIEW

**Comment by okx-code** [comment]
Could we disable canStorageTeleport instead?

**Comment by drekamor** [comment]
I don't know why we have it so I've made a solution that wouldn't affect it in any way :man_shrugging:

**Comment by okx-code** [comment]
It should be safe to removed based on the commit history  https://github.com/CivMC/Civ/commit/0a9b5b4568b65cb3083ef24fc26fb4135f98f381

**Comment by drekamor** [comment]
Well, then you can do that. Discovering the cause of the bug was the hard part here. Took 5 minutes to write that code anyway

**Comment by okx-code** [comment]
Alright

**Pull request closed without merging**
