### PR TITLE
Add Kotlin support

### PR DESCRIPTION
**Pull request by Protonull**
Standardises any Kotlin support

### CODE REVIEW

**Comment by okx-code** [comment]
What is the use case for this?

**Comment by Protonull** [comment]
> What is the use case for this?

Being able to code in Kotlin?

**Comment by okx-code** [comment]
What specifically do you want to use this for?

**Comment by AngrySoundTech** [comment]
This should be added with something that uses it, not on it's own

**Comment by Protonull** [comment]
> What specifically do you want to use this for?

1. For when Kira gets added.

2. While I know there was a discussion about not mixing Java and Kotlin within the same plugin, I nonetheless think converting the `NBTTagCompoundExtensions` class (and its ilk) over to Kotlin's extension methods is the only sensible option. Very little will change from Java's perspective, but it'll be all the better for any plugin that has Kotlin code and needs to use those utilities.

3. I wanna refactor ItemExchange into Kotlin :) I know this is kind of a meme, but if we can't mix Java and Kotlin within the same plugin, and refactoring a plugin into Kotlin is a meme, then is Kotlin support only being added for Kira and that's it?

**Pull request closed without merging**
