### PR TITLE
Refactor DogFacts to use MiniMessage

### PR DESCRIPTION
**Pull request by Protonull**
Moving https://github.com/CivMC/SimpleAdminHacks/pull/76 over to here.

### CODE REVIEW

**Review by okx-code — APPROVED** [review]
looks good, but does dogfacts really broadcast at random intervals, determined on restart? wtf?

**Comment by RedDevel2** [comment]
Really? Then why is there an interval time in the config?

**Comment by okx-code** [comment]
Oh it's just the inital delay, not the interval. Still weird but ok I guess

**Comment by Protonull** [comment]
Is there anything in particular preventing this from being merged since it's missed two assigned milestones?

**Comment by okx-code** [comment]
The current dog facts config would need to be changed

**Comment by Protonull** [comment]
> The current dog facts config would need to be changed

Done

**Review by okx-code — APPROVED** [review]

**Pull request merged**
